---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myendproject
  labels:
    app: myendproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myendproject
  template:
    metadata:
      name: myendproject-pod
      labels:
        app: myendproject
    spec:
      containers:
        - name: myendproject
          image: mrtienvu/endprojectimage
          resources:
            limits:
              cpu: 20m ## 10% of 1 core on your system

---

apiVersion: v1
kind: Service
metadata:
  name: myendproject-svc
spec:
  type: ClusterIP
  selector:
    app: myendproject
  ports:
   - protocol: TCP
     port: 8088
     targetPort: 8088

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myendproject-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myendproject
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
