---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myendproject-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myendproject
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
