---
kind: Service
apiVersion: v1
metadata:
  name: deploytest-service
spec:
  type: NodePort
  selector:
    app: deploytest
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30880

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploytest
  labels:
    app: deploytest
spec:
  selector:
    matchLabels:
      app: deploytest
  template:
    metadata:
      name: deploytest
      labels:
        app: deploytest
    spec:
      containers:
        - name: deploytest
          image: mrtienvu/endprojectimage
