---
kind: Service
apiVersion: v1
metadata:
  name: myendproject-service
spec:
  type: NodePort
  selector:
    app: myendproject
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30881

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myendproject
  labels:
    app: myendproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myendproject
  template:
    metadata:
      name: myendprojectpod
      labels:
        app: myendproject
    spec:
      containers:
        - name: myendproject
          image: mrtienvu/endprojectimage
