---
apiVersion: v1
kind: Service
metadata:
  name: myendproject-service
spec:
  type: ClusterIP
  selector:
    app: myendproject
  ports:
   - protocol: TCP
     port: 8088
     targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myendproject
  labels:
    app: myendproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myendproject
  template:
    metadata:
      name: myendprojectpod
      labels:
        app: myendproject
    spec:
      containers:
        - name: myendproject
          image: mrtienvu/endprojectimage
          resources:
            limits:
              cpu: 20m
