---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myendproject
  labels:
    app: myendproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myendproject
  template:
    metadata:
      name: myendprojectpod
      labels:
        app: myendproject
    spec:
      containers:
        - name: myendproject
          image: mrtienvu/endprojectimage
